// Version
export { SCHEMA_VERSION } from './version.js';

// Auth
export {
  AuthRegisterRequestSchema,
  AuthRegisterResponseSchema,
  AuthLoginRequestSchema,
  AuthLoginResponseSchema,
  AuthRefreshRequestSchema,
  AuthRefreshResponseSchema,
  InventorySchema,
  ProgressionSchema,
  ProfileResponseSchema,
  FortressClassSchema,
  HeroIdSchema,
  TurretTypeSchema,
  DefaultLoadoutSchema,
  CompleteOnboardingRequestSchema,
  CompleteOnboardingResponseSchema,
  type AuthRegisterRequest,
  type AuthRegisterResponse,
  type AuthLoginRequest,
  type AuthLoginResponse,
  type AuthRefreshRequest,
  type AuthRefreshResponse,
  type Inventory,
  type Progression,
  type ProfileResponse,
  type FortressClassType,
  type HeroIdType,
  type TurretTypeType,
  type DefaultLoadout,
  type CompleteOnboardingRequest,
  type CompleteOnboardingResponse,
} from './auth.js';

// Events
export {
  ChooseRelicEventSchema,
  RerollRelicsEventSchema,
  ActivateSnapEventSchema,
  GameEventSchema,
  CheckpointSchema,
  type ChooseRelicEvent,
  type RerollRelicsEvent,
  type ActivateSnapEvent,
  type GameEvent,
  type Checkpoint,
} from './events.js';

// Runs
export {
  RunStartResponseSchema,
  RunFinishRequestSchema,
  RunRewardsSchema,
  RunFinishResponseSchema,
  RUN_REJECTION_REASONS,
  type RunStartResponse,
  type RunFinishRequest,
  type RunRewards,
  type RunFinishResponse,
  type RunRejectionReason,
} from './runs.js';

// Leaderboard
export {
  LeaderboardEntrySchema,
  LeaderboardQuerySchema,
  LeaderboardResponseSchema,
  type LeaderboardEntry,
  type LeaderboardQuery,
  type LeaderboardResponse,
} from './leaderboard.js';

// Telemetry
export {
  TelemetryEventSchema,
  TelemetryBatchRequestSchema,
  TelemetryBatchResponseSchema,
  TELEMETRY_EVENTS,
  type TelemetryEvent,
  type TelemetryBatchRequest,
  type TelemetryBatchResponse,
  type TelemetryEventType,
} from './telemetry.js';

// Sessions
export {
  SessionStartRequestSchema,
  SessionEndRequestSchema,
  UpdateLoadoutRequestSchema,
  ProgressionBonusesSchema,
  SessionStartResponseSchema,
  SegmentSubmitRequestSchema,
  SegmentSubmitResponseSchema,
  PartialRewardsSchema,
  SessionEndResponseSchema,
  type SessionStartRequest,
  type SessionEndRequest,
  type UpdateLoadoutRequest,
  type ProgressionBonuses,
  type SessionStartResponse,
  type SegmentSubmitRequest,
  type SegmentSubmitResponse,
  type PartialRewards,
  type SessionEndResponse,
} from './sessions.js';

// Upgrades
export {
  UpgradeHeroRequestSchema,
  UpgradeHeroResponseSchema,
  UpgradeTurretRequestSchema,
  UpgradeTurretResponseSchema,
  HERO_UPGRADE_COSTS,
  TURRET_UPGRADE_COSTS,
  type UpgradeHeroRequest,
  type UpgradeHeroResponse,
  type UpgradeTurretRequest,
  type UpgradeTurretResponse,
} from './upgrades.js';

// Artifacts
export {
  PlayerArtifactSchema,
  PlayerItemSchema,
  ArtifactsResponseSchema,
  CraftArtifactRequestSchema,
  CraftArtifactResponseSchema,
  EquipArtifactRequestSchema,
  EquipArtifactResponseSchema,
  UnequipArtifactRequestSchema,
  UnequipArtifactResponseSchema,
  UseItemRequestSchema,
  UseItemResponseSchema,
  type PlayerArtifact,
  type PlayerItem,
  type ArtifactsResponse,
  type CraftArtifactRequest,
  type CraftArtifactResponse,
  type EquipArtifactRequest,
  type EquipArtifactResponse,
  type UnequipArtifactRequest,
  type UnequipArtifactResponse,
  type UseItemRequest,
  type UseItemResponse,
} from './artifacts.js';

// Heroes (unlock/recruit)
export {
  HeroRaritySchema,
  HERO_UNLOCK_COSTS,
  TURRET_UNLOCK_COST,
  FREE_STARTER_HEROES,
  FREE_STARTER_TURRETS,
  UnlockHeroRequestSchema,
  UnlockHeroResponseSchema,
  UnlockTurretRequestSchema,
  UnlockTurretResponseSchema,
  type HeroRarity,
  type UnlockHeroRequest,
  type UnlockHeroResponse,
  type UnlockTurretRequest,
  type UnlockTurretResponse,
} from './heroes.js';

// Boss Rush
export {
  BossRushStartRequestSchema,
  BossRushStartResponseSchema,
  BossRushSummarySchema,
  BossRushFinishRequestSchema,
  BossRushRewardsSchema,
  BossRushFinishResponseSchema,
  BossRushLeaderboardEntrySchema,
  BossRushLeaderboardQuerySchema,
  BossRushLeaderboardResponseSchema,
  BossRushHistoryEntrySchema,
  BossRushHistoryQuerySchema,
  BossRushHistoryResponseSchema,
  BOSS_RUSH_REJECTION_REASONS,
  type BossRushStartRequest,
  type BossRushStartResponse,
  type BossRushSummary,
  type BossRushFinishRequest,
  type BossRushRewards,
  type BossRushFinishResponse,
  type BossRushLeaderboardEntry,
  type BossRushLeaderboardQuery,
  type BossRushLeaderboardResponse,
  type BossRushHistoryEntry,
  type BossRushHistoryQuery,
  type BossRushHistoryResponse,
  type BossRushRejectionReason,
} from './boss-rush.js';

// Power Upgrades
export {
  // Shared schemas
  StatUpgradesSchema,
  ItemTierSchema,
  FortressUpgradableStatSchema,
  HeroUpgradableStatSchema,
  TurretUpgradableStatSchema,
  // Request schemas
  UpgradeFortressStatRequestSchema,
  UpgradeHeroStatRequestSchema,
  UpgradeTurretStatRequestSchema,
  UpgradeItemTierRequestSchema,
  // Response schemas
  PowerUpgradeResponseSchema,
  PowerBreakdownSchema,
  EntityPowerSchema,
  PowerSummaryResponseSchema,
  UpgradeCostInfoSchema,
  AvailableUpgradesResponseSchema,
  // Types
  type StatUpgrades as PowerStatUpgrades,
  type ItemTier as PowerItemTier,
  type FortressUpgradableStat,
  type HeroUpgradableStat as PowerHeroUpgradableStat,
  type TurretUpgradableStat as PowerTurretUpgradableStat,
  type UpgradeFortressStatRequest,
  type UpgradeHeroStatRequest,
  type UpgradeTurretStatRequest,
  type UpgradeItemTierRequest,
  type PowerUpgradeResponse,
  type PowerBreakdown,
  type EntityPower,
  type PowerSummaryResponse,
  type UpgradeCostInfo,
  type AvailableUpgradesResponse,
} from './power-upgrades.js';

// PvP Arena
export {
  PvpChallengeStatusSchema,
  PvpWinReasonSchema,
  PvpCreateChallengeRequestSchema,
  PvpChallengeSchema,
  PvpCreateChallengeResponseSchema,
  PvpChallengesQuerySchema,
  PvpChallengesResponseSchema,
  PvpAcceptResponseSchema,
  PvpBattleStatsSchema,
  PvpResultSchema,
  PvpChallengeWithResultSchema,
  PvpOpponentsQuerySchema,
  PvpOpponentSchema,
  PvpOpponentsResponseSchema,
  PvpReplayRequestSchema,
  PvpReplayResponseSchema,
  PvpUserStatsSchema,
  PVP_CONSTANTS,
  PVP_ERROR_CODES,
  type PvpChallengeStatus,
  type PvpWinReason,
  type PvpCreateChallengeRequest,
  type PvpChallenge,
  type PvpCreateChallengeResponse,
  type PvpChallengesQuery,
  type PvpChallengesResponse,
  type PvpAcceptResponse,
  type PvpBattleStats,
  type PvpResult,
  type PvpChallengeWithResult,
  type PvpOpponentsQuery,
  type PvpOpponent,
  type PvpOpponentsResponse,
  type PvpReplayRequest,
  type PvpReplayResponse,
  type PvpUserStats,
  type PvpErrorCode,
} from './pvp.js';
