-- AlterTable
ALTER TABLE "MetricSnapshot" ADD COLUMN "responseTimeAvg" DOUBLE PRECISION,
ADD COLUMN "responseTimeP50" DOUBLE PRECISION,
ADD COLUMN "responseTimeP95" DOUBLE PRECISION,
ADD COLUMN "responseTimeP99" DOUBLE PRECISION,
ADD COLUMN "responseTimeMax" DOUBLE PRECISION,
ADD COLUMN "queueWaitingTotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "queueActiveTotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "queueDelayedTotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "queueFailedTotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "queueMetricsJson" JSONB;
